name: rebeldecibel
favicon: null
layout_spectrum: 0.16233
typography_spectrum: 0.17033
title: REBEL DECIBEL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f9f6'
    - '#6e679a'
    - '#0e1d32'
    - '#a99e8a'
    - '#c253bf'
  brandStrength: 0.6171218561939895
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.12514361599460244
purpose: []
